language: node_js

node_js:
  - "node"

env:
  env:
  - CODECLIMATE_REPO_TOKEN=f6086c3920602d6e039ca0a214e2b9696059a68ef8272c68f57c33dd8466940d

before_script:
  - npm install -qg grunt-cli karma-cli istanbul codeclimate-test-reporter

script:
  - npm test

after_script:
  - codeclimate < test/coverage/**/lcov.info